### ISSUE TITLE
Hikari is a connection pool and doesn't need to be initialized for every query

### ISSUE THREAD

**Issue by DSeeLP** [JuliGames/Juliono#1]
`HikariDataSource` is a pooled data source that creates new connections as needed. (See `HikariDataSource#getConnection`)
It should not be created and closed for every query.
And `Connection#close` should never be called, because that handles hikari automatically.
This could also be a possible memory leak because a `HikariDataSource` is never closed.

See https://github.com/JuliGames/Juliono/blob/main/src/main/java/flustix/juliono/database/Database.java#L25

**Comment by TureBentzin** [comment]
Yea seems legit and should be fixed for performance reasons

**Comment by flustix** [comment]
fixed! ([d25a776](https://github.com/JuliGames/Julino/commit/d25a776f4154e7efcbac8221826f5a201b78800d))

**Comment by flustix** [comment]
nvm i didnt really fix it
